title: HRV-Mart Documentaion
description: Documentation for HRV-Mart
theme: just-the-docs

baseurl: "/docs"
url: https://hrv-mart.github.io/docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
