title: HRV-Mart Documentaion
description: Documentation for HRV-Mart
theme: just-the-docs
color_scheme: dark
baseurl: "/docs"
url: https://hrv-mart.github.io/docs

aux_links:
  GitHub: https://github.com/HRV-Mart
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
