title: HRV-Mart Documentaion
description: Documentation for HRV-Mart
theme: just-the-docs
color_scheme: dark
baseurl: "/docs"
url: https://hrv-mart.github.io/docs

aux_links:
  HRV-Mart-GitHub: https://github.com/HRV-Mart
  Discord: https://discord.gg/w5jbhq3juh
  Reddit: https://www.reddit.com/r/HRV_Mart
